dev-rogii-v1.0.0 add cmake build scripts
rogii-com/compact_enc_det pull request #1
Opened 2019-11-07 08:56 UTC by mmaulwurff

2019-11-07 09:13 UTC, chak3r commented on cmake/package/build_common.cmake
> +    "${BASE_BUILD_PATH}/lib"
а мы через install цель не можем сделать, подправив их cmakelists, чтобы не копировать все либы и все хидеры?

2019-11-07 09:42 UTC, mmaulwurff commented on cmake/package/build_common.cmake
> +    "${BASE_BUILD_PATH}/lib"
Не стал править их CMakeLists чтобы не было проблем с потенциальным обновлением библиотеки. На мой взгляд, наличие копирования здесь не критично.

2019-11-12 09:36 UTC, gshep requested changes

2019-11-12 09:36 UTC, gshep commented on cmake/package/package.cmake
> +    compact_enc_det::library
i suggest just `compact_enc_det`

2019-11-12 09:36 UTC, gshep commented on cmake/package/build_common.cmake
> +    ${CMAKE_COMMAND} -S . -B "${BASE_BUILD_PATH}" -A "${ARCH_PARAMETER}"
i don't understand this command. What does it do?

2019-11-12 09:38 UTC, mmaulwurff commented on cmake/package/package.cmake
> +    compact_enc_det::library
Noted, will be changed.

2019-11-12 10:26 UTC, mmaulwurff commented on cmake/package/package.cmake
> +    compact_enc_det::library
Done.

2019-11-12 10:32 UTC, gshep requested changes

2019-11-12 10:32 UTC, gshep commented on cmake/version/Version.cmake
>      COMPACT_ENC_DETG_VERSION_PATCH
misprint in var name =(

2019-11-12 10:36 UTC, mmaulwurff commented on cmake/version/Version.cmake
>      COMPACT_ENC_DETG_VERSION_PATCH
Fixed.

2019-11-12 10:55 UTC, merged