Updated build scripts
rogii-com/compact_enc_det pull request #5
Opened 2021-09-29 05:17 UTC by Shkarlatov

2021-10-01 13:57 UTC, mr-bit requested changes
Main CMakeLists.txt file doesn't contain usage of cnpm and environment.cmake

2021-10-01 13:57 UTC, mr-bit commented on rogii/environment.cmake
> +    include(${CMAKE_CURRENT_LIST_DIR}/environment_linux.cmake)
environment_linux.cmake is empty, add
```
CNPM_ADD_PACKAGE(
    NAME
        gxx_runtime
    VERSION
        9.2.1
    BUILD_NUMBER
        0
)
```

2021-10-04 11:23 UTC, mr-bit approved these changes

2021-10-05 05:55 UTC, chak3r requested changes

2021-10-05 05:55 UTC, chak3r commented on rogii/build_common.cmake
> +file(
This is a duplicate of the code above

2021-10-05 06:07 UTC, chak3r approved these changes

2021-10-05 11:57 UTC, merged